In [3]:
import numpy as np

# Import the numpy module

# Create a numpy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print(arr)

# Perform basic operations on the array
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))

[1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951


In [4]:
import numpy as np

# Create a 3-dimensional array
tensor = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

# Print the tensor
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [5]:
# Access a particular element in the numpy array
element = arr[2]

# Print the element
print(element)

3


In [6]:
first_row_submatrix1 = tensor[0, 0]
first_row_submatrix2 = tensor[1, 0]

print("First row of submatrix 1:", first_row_submatrix1)
print("First row of submatrix 2:", first_row_submatrix2)

First row of submatrix 1: [1 2 3]
First row of submatrix 2: [7 8 9]


In [7]:
last_row_submatrix1 = tensor[0, 1]
last_row_submatrix2 = tensor[1, 1]

print("Last row of submatrix 1:", last_row_submatrix1)
print("Last row of submatrix 2:", last_row_submatrix2)

Last row of submatrix 1: [4 5 6]
Last row of submatrix 2: [10 11 12]
